name: newanalysis-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Base depends
  - python
  - numpy
  - cython
  - scipy
  # docs
  - mock
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - sphinx-gallery
  # for notebooks
  - jupyter
